- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: installed 
  
  - name: starting nginx service
    ansible.builtin.service:
      name: nginx
      state: "started"
      enabled: yes
