#-----PLAY1------
- name: PLAY1
  hosts: local
  connection: local # managing its own node, no need of credentials
  tasks:
  - name: PLAY1 and TASK1
    ansible.builtin.debug:
      msg: "Hello from  PLAY1 and TASK1"

#------PLAY2--------
- name: PLAY2
  hosts: local
  connection: local # managing its own node, no need of credentials
  tasks:
  - name: PLAY2 and TASK1
    ansible.builtin.debug:
      msg: "Hello from  PLAY2 and TASK1"

#--------PLAY3-------
- name: hello world playbook # PlayBook Name
  hosts: local
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "printing hello world text"
  - name: print hello india
    ansible.builtin.debug:
      msg: "printing hello india"