- name: git clone
  hosts: servers
  become: yes
  tasks:
  - name: clone into new repo
    ansible.builtin.git:
      repo: https://github.com/naveenrajoli4/expense_documentation.git
      dest: /home/ec2-user/naveen
      version: main 