- name: Variables
  hosts: local
  connection: local
  vars: # PLAY level variables, global variables
    NAME: "Rajoli Naveen"
    LAST_NAME: "Kumar"
    NUM: "DevOps"
    LOCATION: "india"
  tasks:
  - name: Task 1 
    ansible.builtin.debug:
      msg: "My name is {{ NAME }} {{ LAST_NAME }} , number is {{ NUM }} and my location is {{ LOCATION }}"

  - name: Task2
    vars: # Task level variables, accessible only with in the task. Task variables can override play level variables. Local variables
      NAME: "Hello"
      LAST_NAME: "Naveen"
    ansible.builtin.debug:
      msg: "My name is {{ NAME }} {{ LAST_NAME }} , number is {{ NUM }} and my location is {{ LOCATION }}"





# below is the command to run the script for local host 
#                  ansible-playbook -i inventory.ini <script_name>
# here user and pswd not required bcz its local host 