- name: Variables from files
  hosts: local
  connection: local
  vars_files:  # variables fitch from another file var.yaml files 
  - var.yaml
  tasks:
  - name: Task 1 
    ansible.builtin.debug:
      msg: "My name is {{ NAME }} {{ LAST_NAME }} , number is {{ NUM }} and my location is {{ LOCATION }}"