- name: Variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: NAME
    prompt: "Please enter your name"
  - name: LAST_NAME
    prompt: "Please enter you last name"
  - name: LOCATION
    prompt: "please enter your location"
  - name: NUM
    prompt: "please enter your number"
  tasks:
  - name: Task 1 
    ansible.builtin.debug:
      msg: "My name is {{ NAME }} {{ LAST_NAME }} , number is {{ NUM }} and my location is {{ LOCATION }}"