- name: loops
  hosts: local
  become: yes
  tasks:
  - name: print loops
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: installed
    loop:
    - nginx
    - git
    - gcc
    - mysql
    - zip