- name: installing apps
  hosts: local
  become: yes
  tasks:
  - name: installing apps with loops
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: installed
    loop:
    - nginx
    - git
    - gcc
    - mysql
    - zip








# - name: installing apps
# ansible.builtin.package:
#   name: "{{ item }}"
#   state: absent # its to uninstall the package