- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: shell vs command
    # ansible.builtin.command: ls -ltr > /tmp/output.txt
    ansible.builtin.shell: ls -ltr > /tmp/output.txt 
    
#ansible.builtin.command---> this like running commands from out side. we will not get access to shell,veriables,redirections,pipes,etc.
#ansible.builtin.shell---> it is like you are logging inside the server and executing command.  we can access variables, we can use redirections. we can use pipes
  - name: shell vs command--2
    ansible.builtin.command: ls -ltr
    register: command_result

  - name: print output
    ansible.builtin.debug:
      msg: "{{ command_result }}"